---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['{{ prometheus_name }}:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "{{ role }}-op-node-exporter"
    static_configs:
      - targets: ["{{ elixir_docker_container_name }}:{{ elixir_prometheus_port }}"]

  - job_name: "{{ role }}-exporter"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["{{ elixir_docker_container_name }}:{{ elixir_prometheus_port }}"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:{{ cadvisor_internal_port }}']

  - job_name: 'grafana_agent'
    static_configs:
      - targets: ['grafana_agent:{{ grafana_agent_http_port }}']  # Adjust if necessary
